services:

  grafana:
    image: 'grafana/otel-lgtm:latest'
    profiles:
      - infrastructure
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'

  postgres:
    image: 'postgres:17'
    profiles:
      - infrastructure
    environment:
      - 'POSTGRES_DB=scheduler'
      - 'POSTGRES_PASSWORD=S3cret!'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    profiles:
      - infrastructure
    ports:
      - '6379:6379'

  service:
    container_name: meeting-scheduler
    build:
      context: .
    profiles:
      - application
    ports:
      - '8080:8080'
    depends_on:
      - grafana
      - postgres
      - redis