spring:
  application:
    name: meeting-scheduler

  jpa:
    open-in-view: off

management:
  otlp:
    metrics:
      export:
        url: http://otlp.example.com:4318/v1/metrics

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http;//localhost:4318/v1/traces

    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
