spring:
  application:
    name: meeting-scheduler

  jpa:
    open-in-view: off

  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler
    username: dev
    password: S3cret!
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost

  docker:
    compose:
      profiles:
        active: infrastructure
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
        include-unsampled: true

    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

scalar:
  enabled: true
